services:
  home:
    image: home
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - backend
  graficos:
    image: graficos
    ports:
      - "8002:8002"
    networks:
      - backend
  consultas:
    image: consultas
    ports:
      - "8001:8001"
    networks:
      - backend
  api:
    image: api
    ports:
      - "8000:8000"
    networks:
      - backend
networks:
  backend:
    driver: bridge